config/routes.rb
Rails.application.routes.draw do
  root 'projects#index'

  resources :projects
  resources :tickets do
    resources :comments
  end
  resources :tags
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :users, except: [:new]

end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, presence: true, length: { minimum: 3, maximum: 160 }
  validates :user_id, presence: true
  belongs_to :ticket
  belongs_to :creator, foreign_key: "user_id", class_name: "User"
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:update, :edit, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def new

  end

  def create
    @comment = Comment.new(comment_params)
    @comment.creator = current_user
    @comment.ticket_id = params[:ticket_id]
    if @comment.save
      ticket = @comment.ticket
      ticket.status = params[:ticket_status] if params[:ticket_status] != ""
      ticket.save
      flash[:notice] = "Your comment was successfully created"
      redirect_to @comment.ticket
    else
      render ticket_path(params[:ticket_id])
    end
  end

  def update
    if @comment.update(comment_params)
      if params[:status] != ""
        ticket = @comment.ticket
        ticket.status = params[:status]
        ticket.save
      end
      flash[:notice] = "Your comment was successfully updated"
      redirect_to @comment.ticket
    else
      render 'edit'
    end
  end

  def edit
  end

  def destroy
    @comment.destroy
  end

  private

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:body)
  end

  def require_same_user
    if current_user != @comment.creator
      flash[:alert] = "You can only edit or delete your own comment"
      redirect_to @comment.ticket
    end
  end
end

app/views/comments/_comment.html.erb
<% if comment.id %>
  <div class="card" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title"><%= comment.body %></h5>
      <p class="card-text"><em>posted by <%= comment.creator.name %> <%= time_ago_in_words(comment.created_at) %> ago
       <%= comment.updated_at != comment.created_at ? "- updated #{time_ago_in_words(comment.updated_at)} ago" : ''%></em></p>
      <%= link_to 'Edit', edit_ticket_comment_path(comment.ticket, comment.id) %>
    </div>
  </div>
  <br>
<% end %>

app/views/comments/_form.html.erb
<%= form_for [@ticket, comment] do |f| %>
  <div class="form-group">
    <%= f.label :body, "Add a comment" %>
    <%= f.text_area :body, id: :comment_body, class: 'form-control'%>
  </div>

  <div class="form-group">
    <%= label_tag :ticket_status, "Update ticket status" %>
    <%= select_tag :ticket_status, options_for_select(Ticket::STATUSES),
                   {prompt: 'Do not change', class: 'form-control'} %>
  </div>

  <div class="actions">
    <%= f.submit class: 'btn btn-primary'%>
    or
    <%= link_to "Cancel", ticket_path(@ticket) %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<%= render 'shared/header', title: "Comment"  %>
<%= render 'shared/errors', object: @comment %>

<%= form_for [@comment.ticket, @comment] do |f| %>
  <div class="form-group">
    <%= f.label :body, "Edit comment" %>
    <%= f.text_area :body, id: :comment_body, class: 'form-control'%>
  </div>

  <div class="form-group">
    <%= label_tag :ticket_status, "Update ticket status" %>
    <%= select_tag :ticket_status, options_for_select(Ticket::STATUSES),
                   {prompt: 'Do not change', class: 'form-control'} %>
  </div>

  <div class="actions">
    <%= f.submit 'Update Comment', class: 'btn btn-primary'-%>
    or
    <%= link_to "Cancel", @comment.ticket %>
  </div>
<% end %>