config/routes.rb
Rails.application.routes.draw do
  root 'projects#index'

  resources :projects
  resources :tickets do
    resources :comments
  end
  resources :tags
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :users, except: [:new]

end

app/models/ticket.rb
class Ticket < ApplicationRecord
  STATUSES = %w(new blocked in_progress fixed)
  validates :title, presence: :true
  validates :body, presence: :true
  validates :status, inclusion: %w(new blocked in_progress fixed)
  belongs_to :project

  has_many :ticket_tag
  has_many :tags, through: :ticket_tag

  has_many :comments, dependent: :destroy
  accepts_nested_attributes_for :comments
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :get_ticket, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:index, :show]

  def index
    @tickets = filter(Ticket.all)
    @project_names = Project.all.map{|project| project[:title]}
  end

  def create # TODO: switch user_id to creator
    @ticket = Ticket.new(ticket_params)
    @ticket.status = params[:status]
    @ticket.user_id = current_user.id
    if @ticket.save
      flash[:notice] = "Ticket was successfully created."
      redirect_to @ticket
    else
      render 'new'
    end
  end

  def new
    @ticket = Ticket.new()
  end

  def edit
  end

  def show
    @comment = Comment.new
  end

  def update
    if @ticket.update(ticket_params)
      flash[:notice] = "Ticket was successfully created."
      redirect_to @ticket
    else
      render 'new'
    end
  end

  def destroy
    @ticket.destroy
    flash[:notice] = "'#{@ticket.title}' was deleted."
    redirect_to tickets_path
  end

  private

  def ticket_params
    params.require(:ticket).permit(:title, :body, :project_id, :assignee_id, tag_ids: [])
  end

  def get_ticket
    @ticket = Ticket.find(params[:id])
  end

  def filter(tickets)
    tag_id = params[:tag]
    project_id = params[:project]
    status = params[:status]
    return tickets if !tag_id && !project_id && !status
    tickets.select do |ticket|
      (tag_id.length == 0 || ticket.tags.map { |tag| tag.id.to_s }.include?(tag_id)) &&
      (project_id.length == 0 || ticket.project_id.to_s == project_id) &&
      (status.length == 0 || ticket.status == status)
    end
  end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_filter.html.erb
<%= form_with(url: tickets_path, local: true, class: "d-flex justify-content-around", method: :get) do |f| %>
<div class="form-group row">
  <label for="project">Show Tickets from
  </label>
  <%= select_tag :project, options_from_collection_for_select(Project.all, :id, :title, params[:project]), include_blank: "All Projects"%>
</div>
<div class="form-group row">
  <label for="status">
    with status
  </label>
  <%= select_tag :status, options_for_select(Ticket::STATUSES.map{|t| [t.titleize, t]}, params[:status]), include_blank: "Any Status" %>

</div>
<div class="form-group row">
  <label for="tag">
    tagged
  </label>
  <%= select_tag :tag, options_from_collection_for_select(Tag.all, :id, :title, params[:tag]), include_blank: "-" %>  
</div>
<%= button_tag 'Update', name: nil, class: "btn btn-primary"%>
|
<%= link_to 'Clear Filter', tickets_path%>
<% end %>

app/views/tickets/_form.html.erb
<%= form_with(model: @ticket, local: true) do |f| %>
  <div class="form-group">
    <%= f.label :project_id %>
    <%= f.collection_select :project_id, Project.all, :id, :title, {class: 'form-control'}%>
  </div>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control'%>
  </div>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: 'form-control'%>
  </div>
  <!-- TODO: fix tags and assignee -->
  <div class="form-group">
    <%= f.label :status %>
    <%= select_tag :status, options_for_select(Ticket::STATUSES), {class: 'form-control'} %>
  </div>
  <div class="form-group">
    <%= f.label :assignee %>
    <%= f.collection_select(:assignee_id, User.all, :id, :name,
      {prompt: 'Make your selection from the list below (can be empty)'},
      { class: "custom-select"}) %>
  </div>
  <div class="form-group">
    <%= f.label :tags %>
    <%= f.collection_select(:tag_ids, Tag.all, :id, :title,
      {prompt: 'Make your selection from the list below (can be empty)'},
      {multiple: true, class: "custom-select"}) %>
  </div>

  <%= f.submit class: "btn btn-primary"%>
<% end %>

app/views/tickets/_table.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Assignee</th>
      <th>Status</th>
      <th>Tags</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @tickets.each.with_index do |ticket, index| %>
      <tr>
        <td><%= link_to ticket.title, ticket %></td>
        <!-- TODO: associate Assignee and User -->
        <td><%= ticket.assignee_id ? User.find(ticket.assignee_id).name : '-' %></td>
        <td><%= ticket.status %></td>
        <td><%= render ticket.tags, last_tag: ticket.tags[-1]%>
        </td>
        <% if logged_in? %>
          <td>
            <%= link_to 'Edit', edit_ticket_path(ticket) %>
             |
            <%= link_to 'Delete', ticket, method: :delete, data: { confirm: "Are you sure?" } %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tickets/edit.html.erb
<%= render 'shared/header', title: "Editing #{@ticket.title}" %>
<%= render 'shared/errors', object: @ticket%>
<br>
<%= render 'form' %>

app/views/tickets/index.html.erb
<%= render 'shared/header', title: 'Tickets' %>
<% if logged_in? %>
  <p><%= link_to 'New Ticket', new_ticket_path %></p>
<% end %>

<%= render 'filter' %>

<%= render 'table', tickets: @tickets %>

app/views/tickets/new.html.erb
<%= render 'shared/header', title: 'New Ticket' %>
<%= render 'shared/errors', object: @ticket%>
<br>

<%= render 'form' %>

app/views/tickets/show.html.erb
<%= render 'shared/header', title: @ticket.title %>
<%= render 'shared/errors', object: @comment%>
<h3>Tags: <%= render @ticket.tags, last_tag: @ticket.tags[-1] %></h3>

<% if logged_in? %>
  <%= link_to 'Edit', edit_ticket_path %>
   |
  <%= link_to 'Delete', @project, method: :delete, params: @ticket, data: { confirm: "Are you sure?" } %>
<% end %>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Status</th>
      <th scope="col">Creator</th>
      <th scope="col">Assignee</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @ticket.status %></td>
      <!-- TODO: associate Assignee and User -->
      <td><%= User.find(@ticket.user_id).name%></td>
      <!-- TODO: associate Assignee and User -->
      <td><%= @ticket.assignee_id ? User.find(@ticket.assignee_id).name : '-' %></td>

    </tr>
  </tbody>
</table>

<h3>Comments: </h3>

<% if @ticket.comments.any? %>
  <%= render @ticket.comments %>
<% end %>

<%= render 'comments/form', comment: @comment %>