config/routes.rb
Rails.application.routes.draw do
  root 'projects#index'

  resources :projects
  resources :tickets do
    resources :comments
  end
  resources :tags
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :users, except: [:new]

end

app/models/project.rb
class Project < ApplicationRecord
  validates :title, presence: :true
  validates :description, presence: :true
  has_many :tickets, dependent: :destroy

  def total_open_tickets
    self.tickets.select { |ticket|  ticket.status != 'fixed'}.count
  end

  def total_tickets
    self.tickets.count
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :get_project, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:index, :show]
  
  def index
    @projects = Project.all
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      flash[:notice] = "Project was successfully created."
      redirect_to @project
    else
      render 'new'
    end
  end

  def new
    @project = Project.new()
  end

  def edit
  end

  def show
    @tickets = @project.tickets
  end

  def update
    if @project.update(project_params)
      flash[:notice] = "Project was successfully created."
      redirect_to @project
    else
      render 'new'
    end
  end

  def destroy
    @project.destroy
    flash[:notice] = "'#{@project.title}' was deleted."
    redirect_to projects_path
  end

  private

  def project_params
    params.require(:project).permit(:title, :description)
  end

  def get_project
    @project = Project.find(params[:id])
  end
end

app/views/projects/_form.html.erb
<%= form_with(model: @project, local: true) do |f| -%>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control'%>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control'%>
  </div>
  <%= f.submit class: "btn btn-primary"%>
<% end %>

app/views/projects/edit.html.erb
<%= render 'shared/header', title: "Editing #{@project.title}"  %>
<%= render 'shared/errors', object: @project %>
<%= render 'form' %>
<p>
  <%= link_to "Show", @project %> | <%= link_to "Back", projects_path %>
</p>

app/views/projects/index.html.erb
<%= render 'shared/header', title: 'Projects' %>
<% if logged_in? %>
  <p><%= link_to 'New Project', new_project_path %></p>
<% end %>


<table class="table">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Open Tickets</th>
      <th scope="col">Total Tickets</th>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= link_to project.title, project_path(project) %> <br> <%= project.description %></td>
        <td><%= project.total_open_tickets %></td>
        <td><%= project.total_tickets %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/projects/new.html.erb
<%= render 'shared/header', title: 'New Project' %>
<%= render 'shared/errors', object: @project%>
<br />
<%= render 'form' %>
<%= link_to "Back", projects_path %>

app/views/projects/show.html.erb
<%= render 'shared/header', title: @project.title %>

<p><%= @project.description %></p>

<% if logged_in? %>
  <p>
    <%= link_to 'Edit', edit_project_path(@project) %>
     |
    <%= link_to 'Delete', @project, method: :delete, data: { confirm: "Are you sure?" } %>
  </p>
<% end %>

<h3>Tickets</h3>

<%= render 'tickets/table', tickets: @project.tickets %>