config/routes.rb
Rails.application.routes.draw do
  root 'projects#index'

  resources :projects
  resources :tickets do
    resources :comments
  end
  resources :tags
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :users, except: [:new]

end

app/models/tag.rb
class Tag < ApplicationRecord
  before_save { self.title = title.capitalize }
  validates :title, presence: true, uniqueness: {:case_sensitive => false}
  has_many :ticket_tag
  has_many :tickets, through: :ticket_tag
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :get_tag, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:index, :show]

  def index
    @tags = Tag.all
  end

  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      flash[:notice] = "Tag was successfully created."
      redirect_to tags_path
    else
      render 'new'
    end
  end

  def new
    @tag = Tag.new()
  end

  def edit
  end

  def show
    @tickets = @tag.tickets
  end

  def update
    if @tag.update(tag_params)
      flash[:notice] = "Tag was successfully created."
      redirect_to @tag
    else
      render 'new'
    end
  end

  def destroy
    @tag.destroy
    flash[:notice] = "'#{@tag.title}' was deleted."
    redirect_to tags_path
  end

  private

  def tag_params
    params.require(:tag).permit(:title, :description)
  end

  def get_tag
    @tag = Tag.find(params[:id])
  end

  def capitalize_tag
    params[:title].capitalize!
  end
end

app/views/tags/_tag.html.erb
<%= tag.title %><%= tag.id == last_tag.id ? '' : ', ' %>

app/views/tags/index.html.erb
<%= render 'shared/header', title: 'Tags' %>
<% if logged_in? %>
  <p><%= link_to 'New Tag', new_tag_path %></p>
<% end %>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Tickets</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.title %></td>
        <td><%= link_to tag.tickets.count, tickets_path(tag: tag.id) %></td>
        <% if logged_in? %>
          <td>
            <%= link_to 'Edit', edit_tag_path(tag) %>
             |
            <%= link_to 'Delete', tag, method: :delete %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tags/new.html.erb
<%= render 'shared/header', title: 'New Project' %>
<%= render 'shared/errors', object: @tag%>
<br />

<%= form_with(model: @tag, local: true) do |f| -%>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control'%>
  </div>
  <%= f.submit class: "btn btn-primary"%>
<% end %>